# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b71e7338c194e0c77ac392967942e157b3a5019f752de9fd27842fa2134093b6a4b66b6eba3f2034b5bde516d86ed401d099c0bd3c185ee72dd8beaaa26e8a66

test:
  secret_key_base: cb6b8ad3d4fef9f9b2fe112a60f853e84014a656edf8af1328bad4ee22b69aff5aab9b1f36ae8759d699698804ea17228cfd8592899b7830ef9c6855d44107e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
